apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system

data:
  mapRoles: |
    - rolearn: arn:aws:iam::660035875440:role/eksctl-artify-cluster-nodegroup-ng-...
      groups:
        - system:bootstrappers
        - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

  mapUsers: |
    - userarn: arn:aws:iam::660035875440:user/<YOUR-IAM-USERNAME>
      username: github-user
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-12T08:26:50Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "24730"
  uid: 4bc3f3f2-dab8-409f-b639-9e6177c6a13f
