apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::660035875440:role/eksctl-artify-cluster-nodegroup-ng-...
      groups:
        - system:bootstrappers
        - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::660035875440:user/intern-admin
      username: github-user
      groups:
        - system:masters
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::660035875440:role/eksctl-artify-cluster-nodegroup-ng-...\n  groups:\n    - system:bootstrappers\n    - system:nodes\n  username: system:node:{{EC2PrivateDNSName}}\n","mapUsers":"- userarn: arn:aws:iam::660035875440:user/\u003cYOUR-IAM-USERNAME\u003e\n  username: github-user\n  groups:\n    - system:masters\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2026-04-12T08:26:50Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"24730","uid":"4bc3f3f2-dab8-409f-b639-9e6177c6a13f"}}
  creationTimestamp: "2026-04-12T08:26:50Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "63304"
  uid: 4bc3f3f2-dab8-409f-b639-9e6177c6a13f
