apiVersion: apps/v1
kind: Deployment
metadata:
  name: artify-backend
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: artify-sa
      containers:
        - name: backend
          image: 660035875440.dkr.ecr.ap-south-1.amazonaws.com/artify-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"

          env:
            - name: AWS_REGION
              value: "ap-south-1"
            - name: TABLE_NAME
              value: "Artworks"
